def on_a_pressed():
    Render.jump(mySprite, 60)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_overlap_tile(sprite, location):
    game.splash("LEVEL: 2. PIPE DREAM.")
    tiles.set_current_tilemap(tilemap("""
        level3
    """))
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        myTile9
    """),
    on_overlap_tile)

def on_overlap_tile2(sprite2, location2):
    tiles.set_current_tilemap(tilemap("""
        level2
    """))
    game.splash("LEVEL: UNKNOWN")
    tiles.place_on_random_tile(mySprite, assets.tile("""
        myTile10
    """))
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.stair_west,
    on_overlap_tile2)

mySprite: Sprite = None
mySprite = Render.get_render_sprite_variable()
Render.jump(mySprite)
tiles.set_tilemap(tilemap("""level_1"""))
tiles.place_on_random_tile(mySprite, sprites.dungeon.stair_ladder)
scene.camera_follow_sprite(mySprite)
mySprite.set_stay_in_screen(False)

def on_forever():
    music.play_melody("C C C C C C C C ", 13)
    music.set_volume(255)
forever(on_forever)
my_sprite = sprites.create(img("""
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ....ffff.......
    ....2ff2.......
    ....ffff.......
    .....ff........
    .....ff........
    ....ffff.......
    ...f.ff.f......
    ....ffff.......
    ...f.ff.f......
    ....ffff.......
    ...f.ff.f......
    .....ff........
    ....f..f.......
    ...f....f......
    ...f....f......
    ...f....f......
    ...f....f......
    ...f....f......
    ...f....f......
    ...f....f......
    ...f....f......
    ...f....f......
"""), SpriteKind.enemy)